### ISSUE TITLE
Some insight about how to run a session

### ISSUE THREAD

**Issue by RxLoutre** [passdan/genesequencepractical#2]
Hello Daniel,

It's been several years that I bookmarked your practical because I thought the idea was really nice and funny to introduce bioinformatics and genetic to teenagers. I have finally the occasion to try it out. There will be a science promotion "La fête de la Science" in Toulouse, were we will be introducing Bioinformatique to highschool students. We have 30 min to have a small practial with them, and I would really enjoy, if you don't mind, using a part of your work to animate the session.

In my memories, there was a pdf explaining how a practical was working in details. I would like, if you agree of course, you to describe a bit more the different stages of the practical, so I can have a better idea on how to run it and to see if it's possible for me to do so.

Thanks a lot for your help, and again thanks for that great idea.

Cheers,

Roxane

**Comment by passdan** [comment]
Hi there! Glad that this can be of some use to other people!

In terms of running the session, most of the information should be here: https://passdan.github.io/genesequencepractical/ (I realise now that this link wasn't on the main page, and also that the formatting had got weird). If there's anything specific please ask.

You might be interested in this second session that I've ran that I named PlanetDNA, taking the same ideas but using the DNA sequences as "alien life" that the students hunt for on a bit planet. So the might find algae, or cyanobateria, or some joke ones from movies and we talk about how DNA makes up different species and what it would mean and what those species do.

I haven't written that one up yet but there are some photos and description in https://goo.gl/photos/Mv7DWHxW1NcGoEKy7 as the test run, and also a more updated one here but without description: https://photos.app.goo.gl/L6nbmgfLG4du63gV7
